### ISSUE TITLE
Mention tooling to build micro-frontends

### ISSUE THREAD

**Issue by dschulten** [neuland/micro-frontends#2]
Consider to add a section or a wiki page which mentions tooling to build micro-frontends without browser frameworks:

- [Sveltejs](https://svelte.technology/) compiles to pure js and optionally [custom elements](https://github.com/sveltejs/svelte/pull/811) as well and allows for server-side rendering. 
- [Stenciljs](https://stenciljs.com/) seems to go a similar route and is inspired by sveltejs.

**Comment by naltatis** [comment]
Haven't heard of them before. I'll look into them.
Generelly I'm trying to keep the site as framework/tool agnostic as possible. But it would definitly helpfull for people to also have more concrete examples or a starter-project for a specific stack (see also #4).

**Comment by eavichay** [comment]
More tools for webcomponents:
1. Polymer (https://www.polymer-project.org/)
2. slim.js (http://slimjs.com)
3. skate-js (https://github.com/skatejs/skatejs)
4. x-tag (https://x-tag.github.io/)

**Comment by eavichay** [comment]
Starter kit for slim.js (webpack, typescript or es6) - https://github.com/eavichay/slim-webpack-boilerplate

**Comment by ChristianUlbrich** [comment]
I agree with @naltatis - the whole point of the approach of the _"DOM being the API"_ is, that **every** framework / library that sticks to these conventions can be used. Maintaining a list of "tools", "frameworks" will **neither** be complete, **nor** current. Furthermore including certain tools or not could lead to endless discussions about being biased.

Using the presented approach, you can use any library you want  and it **does not** necessarily have to be _web-component-centric_. We are using this approach with e.g. Angular 5 / Preact ; they do not use themselves the Custom Element API, but still can be used as _components_, because they _behave_ according to the **conventions** presented here.

It is **about software architecture**, not a certain tooling or library. Compare this to for example with MVC as an architecture style - the list of frameworks on http://todomvc.com/ is in no way complete and their issue tracker is flooded by Authors of other MVC implementations.

**Comment by eavichay** [comment]
I tend to agree, but the rising approach of "micro-frontends" does lead to solutions like web-components (IMHO it will eventually get there as the optimal solution) and these aren't treated enough. If libraries or ecosystems that works on top of this API are pushed aside, community will still be afraid to embrace those breakthroughs.

**Comment by ChristianUlbrich** [comment]
Putting things in perspective: Micro-Frontends are an approach, to break the frontend monolith apart in function verticals. Quoting ThoughtWorks:

> In this approach, a web application is broken up by its pages and features, with each feature being owned end-to-end by a single team. [Source](https://www.thoughtworks.com/radar/techniques/micro-frontends)

Achieving this goal can be done in many different ways. Web Components are just one (and don't get me wrong; I think they are the best solution) way of achieving this.

Web Components allow for a complete and sound composition framework; that will ultimately allow to incorporate all [other approaches](https://medium.com/@tomsoderlund/micro-frontends-a-microservice-approach-to-front-end-web-development-f325ebdadc16).

The thing is, we might have different notions of what a Web Component actually is. For me - everything adhering to the outlined conventions - is a Web Component. That is technically speaking every _HTMLUnknownElement_ (i.e. custom tag) that:
* communicates via Events
  * listen for specific _Custom Event_s on itself
  * emits specific _Custom Event_s on just itself (i.e. that do **not** bubble)
* can be parametrized with attributes
* is isolated in itself (i.e. everything can read from a single _bundle file_)
  * and thus should prevent leaking of inner styles, either via Shadow DOM or via scoped styles and ids

But I also agree with you @eavichay the compositional nature of Web Components is not stated clearly enough; although I do not blame @naltatis, because I think so far it simply has not been his goal to present a most generic solution, but a viable one working for his projects so far pretty well. 

I am in the process of using this excellent work and formalizing it for a generic Micro-Frontend(TM) architecture, that we will use for further projects; if only time would be more lenient with me.

**Comment by naltatis** [comment]
Yes, the term "Micro Frontend" as defined by ThoughtWorks describes the an architecture with vertically organized end-to-end teams. On this site I'm describing a way to solve the frontend-integration challenge in the browser with existing web standards.

Facebook [BigPipe](https://www.facebook.com/notes/facebook-engineering/bigpipe-pipelining-web-pages-for-high-performance/389414033919) and Zalando [Mosaic Project](https://www.mosaic9.org/) also implement the Micro Frontend architecture, but they've build a custom integration platform to achieve this. Same goes for [Microservice Websites](https://gustafnk.github.io/microservice-websites/), which describes a more server focused integration solution.

Coming back to the topic of this issue. In my examples Custom Elements are simply used as the boundaries and interface for a teams feature-component. What the teams use internally does not matter (from a system architectures point of view).

Defining a Custom Element by hand is quite simple, as I've tried to show in the article. I don't think we need additional tool-support here.

I would really like a future where we don't need special tools/frameworks to build good browser software. But we aren't there yet. I think Evan You (creator of Vue) [summarized it aptly](https://hacks.mozilla.org/2015/06/the-state-of-web-components/#comment-17855):

> The problem is two-fold: people want component-oriented development experience, and interoperability. Currently web component is trying to solve both of them, but it turns out that it doesn’t solve the development experience issue very well on its own. IMO it is better if the spec focus on interoperability alone, and leave the dev experience part to frameworks.
